### ISSUE TITLE
Source code was not found for app:///main.jsbundle

### ISSUE THREAD

**Issue by lefloh** [getsentry/sentry-fastlane-plugin#44]
Hi, I'm not able to link the sourcemaps of a React Native application correctly. Please let me know if you prefer these kind of issues on StackOverflow.

Version: `1.5.0`

Sentry is self hosted.

**Usage:**

    sentry_upload_file(
      app_identifier: "my.company.App",
      file: "./ios/main.jsbundle",
      version: "x.x.x"
    )
    sentry_upload_sourcemap(
      app_identifier: "my.company.App",
      sourcemap: "./ios/main.jsbundle.map",
      rewrite: true,
      version: "x.x.x"
    )

**Output:**

    --------------------------------
    --- Step: sentry_upload_file ---
    --------------------------------
    sentry-cli 1.39.1 installed!
    No config provided, will fallback to .sentryclirc
    Starting sentry-cli...
    A afa59f1798354779b19cc40c89d3f3937eb8e1cf  (4943497 bytes)
    Successfully uploaded files to release: my.company.App-x.x.x
    -------------------------------------
    --- Step: sentry_upload_sourcemap ---
    -------------------------------------
    sentry-cli 1.39.1 installed!
    No config provided, will fallback to .sentryclirc
    Starting sentry-cli...
    > Analyzing 1 sources
    > Rewriting sources
    > Adding source map references
    > Uploading source maps for release my.company.App-x.x.x
    Source Map Upload Report
    Source Maps
    ~/main.jsbundle.map
    Successfully uploaded files to release: my.company.App-x.x.x

**Error Message:**

<img width="1013" alt="error-message" src="https://user-images.githubusercontent.com/1819274/53474191-b93a5e80-3a6c-11e9-94d5-d90e92c08b4e.png">

When I follow the "Release: x.x.x" link I can see the following artifacts:

<img width="1323" alt="files" src="https://user-images.githubusercontent.com/1819274/53474211-c35c5d00-3a6c-11e9-8495-e6d79dd0ae71.png">

So I doubt that there's a problem with missing files, a wrong `app_identifier` or version number. Seems like the path is wrong but I don't know how I could control this. Moving the files to the directory from which I'm executing fastlane and using `main.jsbundle(.map)` as filename didn't help.

Thanks in advance.

**Comment by ribamarsantos** [comment]
I was about to suggest a different directory. nbd but could you try with:
`  sourcemap: "./ios/main.jsbundle.map.js"`

Could you share how you're generating your bundle files ? 
It worked with me by executing:
` react-native bundle --platform ios --entry-file <your_entry_file> --dev false --bundle-output ./output/main.ios.jsbundle  --sourcemap-output ./output/main.ios.jsbundle.map.js                
` 
In this case my sourcemap is in another directory.

**Comment by lefloh** [comment]
Thanks a lot for your answer @ribamarsantos!
I was using ```react-native bundle --dev false --platform ios --entry-file ./index.js --bundle-output ./ios/main.jsbundle --sourcemap-output ./ios/main.jsbundle.map```
I tried to add the `.js` extension and will post an update when I'm getting the next Sentry issues.

**Comment by lefloh** [comment]
I've uploaded the sourcemap file as
* `~/main.jsbundle`
* `~/main.jsbundle.map`
* `~/main.jsbundle.map.js`
Unfortunately this did not change anything.

**Comment by mieszko4** [comment]
I have the same issue.
* I see artifacts in `Releases` tab
* I see issue linked to the the right release in `Releases` tab, too
* I've checked release name and build number and it is the same for artifacts and for the issue

I have android and ios release named the same, e.g. `19`, but since my bundle ids are named different it makes two positions in `Releases` list. My build number is the same for both releases.

## For android:
* My artifacts are: `~/index.android.bundle` and `~/index.android.bundle.map`
* The error on the issue is:
```
Source code was not found
Url	
app:///index.android.bundle
```

## For ios:
* My artifacts are: `~/main.jsbundle` and `~/main.jsbundle.map`
* The error on the issue is:
```
Source code was not found
Url	
app:///main.jsbundle
```

Also this problem seems **random**. For my release `18` source maps were linked correctly for the same issue on ios (but still not on android)

I am using `"react-native-sentry": "^0.43.2",`
The releases are https://sentry.io/organizations/kidztopros/releases/com.kidztopros.ktpreact-19/artifacts/?project=1274609 (ios) and https://sentry.io/organizations/kidztopros/releases/com.ktpreact-19/artifacts/?project=1274609 (android)

Could you help me resolve this problem, please?
Is there some way to verify by downloading source maps if they are correct?

**Comment by lefloh** [comment]
I tried to solve the issue with the [sentry-cli](https://github.com/getsentry/sentry-cli) directly by experimenting with the `--url-prefix` param. This way I could change the artifact path but it did not solve the issue.

If it matters: I also have an iOS and Android Release with the same name.

**Comment by LydGol90** [comment]
Hi @lefloh, I was having the exact same issue as you have listed above with iOS. I'm no expert and I have just been trying to make it work by trial and error. For me I managed to fix it by uploading the main.jsbundle with the sourcemaps upload rather then the file upload. My artifacts now look like this: 
<img width="1175" alt="Screenshot 2019-08-05 at 09 38 17" src="https://user-images.githubusercontent.com/29592293/62450744-cd456300-b764-11e9-955b-533504277fb4.png">

Try doing this instead: 
```
sentry_upload_sourcemap(
  app_identifier: "my.company.App",
  file: "./ios/main.jsbundle",
  version: "x.x.x"
)
sentry_upload_sourcemap(
  app_identifier: "my.company.App",
  sourcemap: "./ios/main.jsbundle.map",
  rewrite: true,
  version: "x.x.x"
)
```

All my js crashes are now showing with proper file names and line numbers! I think the key was to have the main.jsbundle and main.jsbundle.map both under ~/

Hope it works for you too!

**Comment by lefloh** [comment]
Thanks @LydGol90 for your help!
I'm confused because I can't find a `file` parameter at `sentry_upload_sourcemap`. My test fails with:

` Could not find option 'file' in the list of available options: url, auth_token, api_key, org_slug, project_slug, version, dist, sourcemap, rewrite, strip_prefix, strip_common_prefix, url_prefix, app_identifier`

**Comment by LydGol90** [comment]
@lefloh Sorry typo! It should just be the same as the sourcemap one so:

```
sentry_upload_sourcemap(
  app_identifier: "my.company.App",
  sourcemap: "./ios/main.jsbundle",
  version: "x.x.x"
)
sentry_upload_sourcemap(
  app_identifier: "my.company.App",
  sourcemap: "./ios/main.jsbundle.map",
  rewrite: true,
  version: "x.x.x"
)
```

**Comment by lefloh** [comment]
OK, thanks. I'll try it and wait for the next error to see if it's working ;-)

**Comment by lefloh** [comment]
Doesn't seem to work here. I'm still getting the error. Maybe it's a problem that I deleted the old sourcemaps and uploaded them again like you described. I'll change it and will have a look with our next release.

**Comment by LydGol90** [comment]
If it's helpful I also came across this command with the Sentry cli which works well for me.

`sentry-cli releases files <VERSION> upload-sourcemaps --bundle ./android/index.android.bundle --bundle-sourcemap ./android/index.android.bundle.map --rewrite`

`sentry-cli releases files <VERSION> upload-sourcemaps --bundle ./ios/main.jsbundle --bundle-sourcemap ./ios/main.jsbundle.map --rewrite`

**Comment by kckunal2612** [comment]
I'm having the exact same issue as described here.
Have you found a solution for this yet @lefloh ?

Here are the npm scripts I use to build sourcemaps -
```
{
"build:ios": "react-native bundle --dev false --platform ios --entry-file index.js --bundle-output ./ios.main.bundle --sourcemap-output ./ios.main.bundle.map",
"build:android": "react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android.main.bundle --sourcemap-output ./android.main.bundle.map"
}  
```

And this is how I am auto-generating source map name in my CI file-
` sourcemap = "#{platform}.main.bundle.map"`

Please find the uploaded artifact file names below -

<img width="686" alt="Screen Shot 2019-09-13 at 3 26 12 PM" src="https://user-images.githubusercontent.com/4411464/64889234-df0b0780-d63a-11e9-9955-f890f28663f9.png">

**Comment by lefloh** [comment]
@kckunal2612 no, still not working for me.

**Comment by vovkasm** [comment]
For me receipt from @LydGol90 works, so this plugin in current state is mostly useless, it is much easier to use `sh` actions and call sentry-cli directly. (

**Comment by zcramos** [comment]
To be clear @vovkasm are you finding that doing what appears to be the same thing with the CLI vs with the fastlane plugin works with CLI but fails with the plugin?

**Comment by aleclarson** [comment]
I'm hitting what's probably the same issue.

Here's the command I used to generate the bundle and its source map:

```sh
react-native bundle \
  --dev false \
  --entry-file index.js \
  --platform macos \
  --bundle-output path/to/main.jsbundle \
  --sourcemap-output path/to/bundle.js.map
```

Here's the command I used to upload them to Sentry:

```sh
sentry-cli releases files <VERSION> upload-sourcemaps \
  --rewrite \
  --strip-common-prefix \
  --validate \
  -x=ts -x=js -x=tsx -x=jsx -x=jsbundle -x=map \
  --bundle path/to/main.jsbundle \
  --bundle-sourcemap path/to/bundle.js.map \
  -u app://
```

The `sentry-cli` command had these logs:

```
  WARN    2019-11-06 14:16:30.060523 -05:00 Regular bundle found
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File processing complete

Source Map Upload Report
  Minified Scripts
    app://main.jsbundle (sourcemap at bundle.js.map)
  Source Maps
    app://bundle.js.map
```

These files appeared in the "Artifacts" page for the relevant release, but none of the errors had resolved `app:///main.jsbundle` in their stack traces. So I deleted the artifacts and tried again, but this time, the files **never appeared** in the "Artifacts" page.

As a last resort, I changed `-u app://` to `-u app:///` to see if that would help, but it didn't. The files appeared (eg: `app:///main.jsbundle`), but the stack traces remained the same.

Any ideas?

### Environment

- `macOS v10.14.5`
- `sentry-cli v1.48.0`
- `node v12.13.0`

**Comment by aleclarson** [comment]
I think the issue stems from the crashed bundle not ending with a source map URL.
```js
//# sourceMappingURL=bundle.js.map
```
The bundle I uploaded with the `upload-sourcemaps` command **does** end with a source map URL, but the bundle I released **did not**.

I'm going to create a new release to verify my suspicion. I'll edit this comment later with my findings.

**Comment by lefloh** [comment]
Still not working for me. I'll close this one now. I spent hours and couldn't solve it and it usually takes only two minutes to find the error without sourcemaps.

**Comment by HelKyle** [comment]
After hours of trying, I finally found a way of making sourcemap work for me.

1. must explicitly call `setRelease`, `setDist` directly, config with init function will not works.

```js
Sentry.init({
  dsn: 'http://7656dac10dd24ba0aeb70e6642acb33d@10.12.162.185:9000/8'
  // release: '0.0.1',   // must be a version string, "my-app@0.0.9" will not works
  // dist: '0.0.1'
})

Sentry.setDist('0.0.1') // dist is required for react-native sentry
Sentry.setRelease('0.0.1')
```

2. should send `jsbundle` and `jsbundle.map` file to sentry both
build the files using react-native bundler
```
react-native bundle --dev false --platform ios --entry-file index.js --bundle-output ./main.jsbundle --sourcemap-output ./main.jsbundle.map
```

send to sentry
```
sentry-cli releases files "0.0.1" upload-sourcemaps --dist "0.0.1" --rewrite ./main.jsbundle ./main.jsbundle.map
```

**Comment by garrett-gottlieb** [comment]
@lefloh why would you close an unresolved issue?

**Comment by kg-currenxie** [comment]
> Try doing this instead:
> 
> ```
> sentry_upload_sourcemap(
>   app_identifier: "my.company.App",
>   sourcemap: "./ios/main.jsbundle",
>   version: "x.x.x"
> )
> sentry_upload_sourcemap(
>   app_identifier: "my.company.App",
>   sourcemap: "./ios/main.jsbundle.map",
>   rewrite: true,
>   version: "x.x.x"
> )
> ```

Worked for me too! Seems to be a bug?

If I use `sentry_upload_file`, i get artifacts without `~/`

![Screenshot 2021-01-28 at 16 04 52](https://user-images.githubusercontent.com/48229166/106108753-a9a98000-6183-11eb-9fbc-37dc70c338ad.png)

**Comment by mklsk** [comment]
Still facing this issue - unclear why the issue was closed

Had to fallback onto calling `sh()` in my Fastfile with the scripts recommended by official sentry docs:

```
        sh("bash cd ../../ && react-native bundle --dev false --platform ios --entry-file index.js --reset-cache --bundle-output main.jsbundle --sourcemap-output main.jsbundle.map")
        sh("bash cd ../../ && sentry-cli releases files  <VERSION> upload-sourcemaps --dist <DIST> --strip-prefix <PATH_TO_PROJECT_ROOT> main.jsbundle main.jsbundle.map")
```
As per: https://docs.sentry.io/platforms/react-native/sourcemaps/
